export const cars = [
  {
    id: 1, 
    brand: "Toyota",
    name: "Corolla",
    type: "sedan",
    capacity: "4 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "economy", price: 50 },
    tankCapacity: "50 liters",
    image: "https://example.com/images/toyota_corolla.jpg"
  },
  {
    id: 2, 
    brand: "BMW",
    name: "X5",
    type: "suv",
    capacity: "6 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 120 },
    tankCapacity: "80 liters",
    image: "https://example.com/images/bmw_x5.jpg"
  },
  {
    id: 3, 
    brand: "Tesla",
    name: "Model S",
    type: "sedan",
    capacity: "4 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 160 },
    tankCapacity: "100 kWh",
    image: "https://example.com/images/tesla_model_s.jpg"
  },
  {
    id: 4, 
    brand: "Mercedes-Benz",
    name: "C-Class",
    type: "sedan",
    capacity: "4 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 100 },
    tankCapacity: "66 liters",
    image: "https://example.com/images/mercedes_c_class.jpg"
  },
  {
    id: 5, 
    brand: "Audi",
    name: "e-tron",
    type: "suv",
    capacity: "6 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 170 },
    tankCapacity: "95 kWh",
    image: "https://cdn.riastatic.com/photosnewr/auto/newauto_photos/audi-sq6-e-tron__1090819-341x224x72.jpg"
  },
  {
    id: 6, 
    brand: "Toyota",
    name: "RAV4",
    type: "suv",
    capacity: "6 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 80 },
    tankCapacity: "55 liters",
    image: "https://images.edealer.ca/2/139465390.jpeg"
  },
  {
    id: 7, 
    brand: "BMW",
    name: "3 Series",
    type: "sedan",
    capacity: "4 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 85 },
    tankCapacity: "55 liters",
    image: "https://www.bmw.ua/content/bmw/marketB4R1/bmw_ua/uk_UA/all-models/3-series/sedan/2022/bmw-3-series-sedan-highlights/jcr:content/par/multicontent_220249867/tabs/multicontenttab_copy/items/smallteaser_945953604/image.transform/smallteaser/image.1667379439504.jpg"
  },
  {
    id: 8, 
    brand: "Tesla",
    name: "Model 3",
    type: "sedan",
    capacity: "4 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 120 },
    tankCapacity: "75 kWh",
    image: "https://platform.cstatic-images.com/xlarge/in/v2/stock_photos/024ed7f5-f035-4a2e-89c1-f6144ee3423c/8a830f62-984b-47aa-87e4-544762d98d4e.png"
  },
  {
    id: 9, 
    brand: "Mercedes-Benz",
    name: "E-Class",
    type: "sedan",
    capacity: "4 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 130 },
    tankCapacity: "70 liters",
    image: "https://example.com/images/mercedes_e_class.jpg"
  },
  {
    id: 10, 
    brand: "Audi",
    name: "Q5",
    type: "suv",
    capacity: "6 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 100 },
    tankCapacity: "70 liters",
    image: "https://example.com/images/audi_q5.jpg"
  },
  {
    id: 11, 
    brand: "Toyota",
    name: "Land Cruiser",
    type: "suv",
    capacity: "8 or more person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 150 },
    tankCapacity: "93 liters",
    image: "https://example.com/images/toyota_land_cruiser.jpg"
  },
  {
    id: 12, 
    brand: "BMW",
    name: "i4",
    type: "sedan",
    capacity: "4 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 150 },
    tankCapacity: "83 kWh",
    image: "https://example.com/images/bmw_i4.jpg"
  },
  {
    id: 13, 
    brand: "Tesla",
    name: "Model X",
    type: "suv",
    capacity: "6 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 200 },
    tankCapacity: "100 kWh",
    image: "https://example.com/images/tesla_model_x.jpg"
  },
  {
    id: 14, 
    brand: "Mercedes-Benz",
    name: "S-Class",
    type: "sedan",
    capacity: "4 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 200 },
    tankCapacity: "80 liters",
    image: "https://example.com/images/mercedes_s_class.jpg"
  },
  {
    id: 15, 
    brand: "Audi",
    name: "A4",
    type: "sedan",
    capacity: "4 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 85 },
    tankCapacity: "60 liters",
    image: "https://example.com/images/audi_a4.jpg"
  },
  {
    id: 16, 
    brand: "Toyota",
    name: "Prius",
    type: "hatchback",
    capacity: "4 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "economy", price: 60 },
    tankCapacity: "8.8 kWh",
    image: "https://example.com/images/toyota_prius.jpg"
  },
  {
    id: 17, 
    brand: "BMW",
    name: "X3",
    type: "suv",
    capacity: "4 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 90 },
    tankCapacity: "60 liters",  
    image: "https://example.com/images/bmw_x3.jpg"  
  },
  { 
    id: 18, 
    brand: "Tesla",
    name: "Model Y",
    type: "suv",
    capacity: "6 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 140 },
    tankCapacity: "82 kWh",   
    image: "https://example.com/images/tesla_model_y.jpg"
  },
  {
    id: 19, 
    brand: "Mercedes-Benz",
    name: "GLA",
    type: "suv",
    capacity: "6 person",
    fuel: "gasoline",
    transmission: "Automatic",
    rentalPrice: { category: "standard", price: 90 },
    tankCapacity: "56 liters",
    image: "https://example.com/images/mercedes_gla.jpg"
  },
  {
    id: 20, 
    brand: "Audi",
    name: "e-tron",
    type: "suv",
    capacity: "6 person",
    fuel: "electric",
    transmission: "Automatic",
    rentalPrice: { category: "luxury", price: 170 },
    tankCapacity: "95 kWh",
    image: "https://example.com/images/audi_etron.jpg"
  }
];
